# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  anykernel-osm0sis = {
    pname = "anykernel-osm0sis";
    version = "020dfeccf9d7e962a48400fc94d3e451df92eead";
    src = fetchFromGitHub {
      owner = "osm0sis";
      repo = "AnyKernel3";
      rev = "020dfeccf9d7e962a48400fc94d3e451df92eead";
      fetchSubmodules = false;
      sha256 = "sha256-OrqaVwNvBXTcXtcS1nLJ78Hw3X88Q+2chjCPtdTdgmM=";
    };
    date = "2026-09-04";
  };
  baseband-guard = {
    pname = "baseband-guard";
    version = "a54e0dc6cf0aff4dd87fec49644a02d2eb612905";
    src = fetchFromGitHub {
      owner = "vc-teahouse";
      repo = "Baseband-guard";
      rev = "a54e0dc6cf0aff4dd87fec49644a02d2eb612905";
      fetchSubmodules = false;
      sha256 = "sha256-ro1Kf3O70KDUfKHm7DnohdhtwXbqU2z9Y1QXNFSJDKo=";
    };
    date = "2026-07-26";
  };
  gcc-aarch64-linux-android = {
    pname = "gcc-aarch64-linux-android";
    version = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
    src = fetchFromGitHub {
      owner = "kindle4jerry";
      repo = "aarch64-linux-android-4.9-bakup";
      rev = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
      fetchSubmodules = false;
      sha256 = "sha256-ZrQmFyiDOKg+qcgdpZqtz+LgDDaao2W27kdZZ2As8XU=";
    };
    date = "2020-02-22";
  };
  gcc-arm-linux-androideabi = {
    pname = "gcc-arm-linux-androideabi";
    version = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
    src = fetchFromGitHub {
      owner = "KudProject";
      repo = "arm-linux-androideabi-4.9";
      rev = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
      fetchSubmodules = false;
      sha256 = "sha256-5aF2Pl+h6J8/5TfQf2ojp3FCnoKakWH6KBCkWdy5ho8=";
    };
    date = "2019-11-25";
  };
  kernelsu-next = {
    pname = "kernelsu-next";
    version = "194a4d0531bba5810a7a0d1014acbbf34d9ae284";
    src = fetchFromGitHub {
      owner = "rifsxd";
      repo = "KernelSU-Next";
      rev = "194a4d0531bba5810a7a0d1014acbbf34d9ae284";
      fetchSubmodules = false;
      sha256 = "sha256-GiUbAxb82sfSzdzcLXC6S1Xm54Oq0KuG0y4U3sKOs9M=";
    };
    date = "2026-09-24";
  };
  kernelsu-next-revision-code = {
    pname = "kernelsu-next-revision-code";
    version = "33294";
    src = fetchurl {
      url = "https://github.com";
      sha256 = "sha256-9IJNI0+1AUPHjKtPRLFJVnb82MBwdp/lO3Kg6ysJilI=";
    };
  };
  linux-poco-f3 = {
    pname = "linux-poco-f3";
    version = "71b13e62f057a649b77fe4062feb73ee72ad609c";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_kernel_xiaomi_sm8250.git";
      rev = "71b13e62f057a649b77fe4062feb73ee72ad609c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-OClxNtfjZU2e8VZt+98pEuY31G9hKP67xqpPatHFMmc=";
    };
    date = "2026-07-13";
  };
}
