# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  anykernel-kernelsu = {
    pname = "anykernel-kernelsu";
    version = "80e0cc9e736572ad16c7dc539ba9b6e40749f8e7";
    src = fetchFromGitHub {
      owner = "Kernel-SU";
      repo = "AnyKernel3";
      rev = "80e0cc9e736572ad16c7dc539ba9b6e40749f8e7";
      fetchSubmodules = false;
      sha256 = "sha256-8zVOkoMXkKQ+SCBg7jYn2H+RP7bb9x8MAOy/8d/P6Cc=";
    };
    date = "2025-11-07";
  };
  anykernel-osm0sis = {
    pname = "anykernel-osm0sis";
    version = "dca9dc370838d919d56c1f59ec78b27a14a72c68";
    src = fetchFromGitHub {
      owner = "osm0sis";
      repo = "AnyKernel3";
      rev = "dca9dc370838d919d56c1f59ec78b27a14a72c68";
      fetchSubmodules = false;
      sha256 = "sha256-J/8RR7xh1fCZDiOSscm1cDWPBU5yFkXLjOHwZxG47Ow=";
    };
    date = "2026-02-25";
  };
  baseband-guard = {
    pname = "baseband-guard";
    version = "886bc0c86be197a1f4d44b8edf895b549bc0e908";
    src = fetchFromGitHub {
      owner = "vc-teahouse";
      repo = "Baseband-guard";
      rev = "886bc0c86be197a1f4d44b8edf895b549bc0e908";
      fetchSubmodules = false;
      sha256 = "sha256-KrS0idcAHbciUPn8CQhlWQ4sYIyYxqzMcSGX+FYpFdg=";
    };
    date = "2026-02-07";
  };
  gcc-aarch64-linux-android = {
    pname = "gcc-aarch64-linux-android";
    version = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
    src = fetchFromGitHub {
      owner = "kindle4jerry";
      repo = "aarch64-linux-android-4.9-bakup";
      rev = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
      fetchSubmodules = false;
      sha256 = "sha256-ZrQmFyiDOKg+qcgdpZqtz+LgDDaao2W27kdZZ2As8XU=";
    };
    date = "2020-02-22";
  };
  gcc-arm-linux-androideabi = {
    pname = "gcc-arm-linux-androideabi";
    version = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
    src = fetchFromGitHub {
      owner = "KudProject";
      repo = "arm-linux-androideabi-4.9";
      rev = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
      fetchSubmodules = false;
      sha256 = "sha256-5aF2Pl+h6J8/5TfQf2ojp3FCnoKakWH6KBCkWdy5ho8=";
    };
    date = "2019-11-25";
  };
  kernelsu-next = {
    pname = "kernelsu-next";
    version = "d8fa0fc817b332260a95d79a7a87d478f239e86f";
    src = fetchFromGitHub {
      owner = "rifsxd";
      repo = "KernelSU-Next";
      rev = "d8fa0fc817b332260a95d79a7a87d478f239e86f";
      fetchSubmodules = false;
      sha256 = "sha256-SMxYxZN/31PnRN+lt369xXQisHL5joyjEDWnslRZ478=";
    };
    date = "2026-03-04";
  };
  kernelsu-next-revision-code = {
    pname = "kernelsu-next-revision-code";
    version = "33024";
    src = fetchurl {
      url = "https://github.com";
      sha256 = "sha256-9IJNI0+1AUPHjKtPRLFJVnb82MBwdp/lO3Kg6ysJilI=";
    };
  };
  linux-poco-f3 = {
    pname = "linux-poco-f3";
    version = "a5b3099017ae581aae8bf597b2f9c8c765026af1";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_kernel_xiaomi_sm8250.git";
      rev = "a5b3099017ae581aae8bf597b2f9c8c765026af1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-R8t014p1F9pouSXD21Tc1d9g1wnA4HYCRTJf+cZBcfA=";
    };
    date = "2026-02-23";
  };
}
